### PR TITLE
Added more details and tips for the simulator. 

### PR DESCRIPTION
**Pull request by RustyRaptor**

### CODE REVIEW

**Comment by auscompgeek** [comment]
The formatting of this looks very odd.

**Comment by auscompgeek** [comment]
@RustyRaptor ping?

**Comment by Sajo8** [comment]
I feel that's github's interpretation of this, VS Code, Dillinger and StackEdit all display with sub-points, probably how OP intended it to be: proper

**Comment by auscompgeek** [comment]
@Sajo8 it looks like in your screenshot that blockquotes are getting rendered there too. I built it with Sphinx and see blockquotes too.

**Comment by Sajo8** [comment]
Yep, seems good to me. I assume the code-block:: js thing is what sphinx needs

**Comment by auscompgeek** [comment]
This simulator is now gone from this season onwards. We now use WPILib's simulation support. Updated docs for the new sim UI is welcome.

**Pull request closed without merging**
